collections = {
    "collections": [
        {
            "collectionCode": "BILLS",
            "collectionName": "Congressional Bills",
            "packageCount": 276493,
            "granuleCount": None,
        },
        {
            "collectionCode": "BILLSTATUS",
            "collectionName": "Congressional Bill Status",
            "packageCount": 161000,
            "granuleCount": None,
        },
        {
            "collectionCode": "BILLSUM",
            "collectionName": "Congressional Bill Summaries",
            "packageCount": 5245,
            "granuleCount": None,
        },
        {
            "collectionCode": "BUDGET",
            "collectionName": "United States Budget",
            "packageCount": 387,
            "granuleCount": 7002,
        },
        {
            "collectionCode": "CCAL",
            "collectionName": "Congressional Calendars",
            "packageCount": 5989,
            "granuleCount": 96335,
        },
        {
            "collectionCode": "CDIR",
            "collectionName": "Congressional Directory",
            "packageCount": 237,
            "granuleCount": 15025,
        },
        {
            "collectionCode": "CDOC",
            "collectionName": "Congressional Documents",
            "packageCount": 53919,
            "granuleCount": 9982,
        },
        {
            "collectionCode": "CFR",
            "collectionName": "Code of Federal Regulations",
            "packageCount": 6433,
            "granuleCount": 7564580,
        },
        {
            "collectionCode": "CHRG",
            "collectionName": "Congressional Hearings",
            "packageCount": 45364,
            "granuleCount": 300,
        },
        {
            "collectionCode": "CMR",
            "collectionName": "Congressionally Mandated Reports",
            "packageCount": 742,
            "granuleCount": None,
        },
        {
            "collectionCode": "COMPS",
            "collectionName": "Statutes Compilations",
            "packageCount": 2617,
            "granuleCount": None,
        },
        {
            "collectionCode": "CPD",
            "collectionName": "Compilation of Presidential Documents",
            "packageCount": 17329,
            "granuleCount": 23012,
        },
        {
            "collectionCode": "CPRT",
            "collectionName": "Congressional Committee Prints",
            "packageCount": 5049,
            "granuleCount": 1850,
        },
        {
            "collectionCode": "CREC",
            "collectionName": "Congressional Record",
            "packageCount": 5762,
            "granuleCount": 827979,
        },
        {
            "collectionCode": "CRECB",
            "collectionName": "Congressional Record (Bound Edition)",
            "packageCount": 2412,
            "granuleCount": 472361,
        },
        {
            "collectionCode": "CRI",
            "collectionName": "Congressional Record Index",
            "packageCount": 43,
            "granuleCount": 624094,
        },
        {
            "collectionCode": "CRPT",
            "collectionName": "Congressional Reports",
            "packageCount": 106350,
            "granuleCount": 569,
        },
        {
            "collectionCode": "CZIC",
            "collectionName": "Coastal Zone Information Center",
            "packageCount": 4887,
            "granuleCount": None,
        },
        {
            "collectionCode": "ECFR",
            "collectionName": "Electronic Code of Federal Regulations",
            "packageCount": 49,
            "granuleCount": None,
        },
        {
            "collectionCode": "ECONI",
            "collectionName": "Economic Indicators",
            "packageCount": 362,
            "granuleCount": 17372,
        },
        {
            "collectionCode": "ERIC",
            "collectionName": "Education Reports from ERIC",
            "packageCount": 573,
            "granuleCount": None,
        },
        {
            "collectionCode": "ERP",
            "collectionName": "Economic Report of the President",
            "packageCount": 40,
            "granuleCount": 2960,
        },
        {
            "collectionCode": "FR",
            "collectionName": "Federal Register",
            "packageCount": 22499,
            "granuleCount": 980194,
        },
        {
            "collectionCode": "GAOREPORTS",
            "collectionName": "Government Accountability Office Reports and Comptroller General Decisions",
            "packageCount": 16569,
            "granuleCount": None,
        },
        {
            "collectionCode": "GOVMAN",
            "collectionName": "United States Government Manual",
            "packageCount": 28,
            "granuleCount": 5129,
        },
        {
            "collectionCode": "GOVPUB",
            "collectionName": "Bulk Submission",
            "packageCount": 114993,
            "granuleCount": 327,
        },
        {
            "collectionCode": "GPO",
            "collectionName": "Additional Government Publications",
            "packageCount": 4325,
            "granuleCount": 80571,
        },
        {
            "collectionCode": "HJOURNAL",
            "collectionName": "Journal of the House of Representatives",
            "packageCount": 153,
            "granuleCount": 33948,
        },
        {
            "collectionCode": "HMAN",
            "collectionName": "House Rules and Manual",
            "packageCount": 25,
            "granuleCount": 2282,
        },
        {
            "collectionCode": "HOB",
            "collectionName": "History of Bills",
            "packageCount": 43,
            "granuleCount": 312849,
        },
        {
            "collectionCode": "LSA",
            "collectionName": "List of CFR Sections Affected",
            "packageCount": 344,
            "granuleCount": 17826,
        },
        {
            "collectionCode": "PAI",
            "collectionName": "Privacy Act Issuances",
            "packageCount": 1590,
            "granuleCount": None,
        },
        {
            "collectionCode": "PLAW",
            "collectionName": "Public and Private Laws",
            "packageCount": 5913,
            "granuleCount": None,
        },
        {
            "collectionCode": "PPP",
            "collectionName": "Public Papers of the Presidents of the United States",
            "packageCount": 180,
            "granuleCount": 24847,
        },
        {
            "collectionCode": "SERIALSET",
            "collectionName": "Congressional Serial Set",
            "packageCount": 146880,
            "granuleCount": None,
        },
        {
            "collectionCode": "SJOURNAL",
            "collectionName": "Journal of the Senate",
            "packageCount": 171,
            "granuleCount": None,
        },
        {
            "collectionCode": "SMAN",
            "collectionName": "Senate Manual",
            "packageCount": 14,
            "granuleCount": 1386,
        },
        {
            "collectionCode": "STATUTE",
            "collectionName": "Statutes at Large",
            "packageCount": 134,
            "granuleCount": 115515,
        },
        {
            "collectionCode": "USCODE",
            "collectionName": "United States Code",
            "packageCount": 1505,
            "granuleCount": 1956865,
        },
        {
            "collectionCode": "USCOURTS",
            "collectionName": "United States Courts Opinions",
            "packageCount": 2002132,
            "granuleCount": 4314960,
        },
    ]
}
